version: '3'
services:
  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  pg:
    image: "postgres:13-alpine"
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./tmp/:/var/lib/postgresql/data/
