version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pg:
    image: "postgres:alpine"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/:/var/lib/postgresql/data/
